import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setvalue] = useState({
    username: "",
    password: "",
  });

  const eventValueOnchang = (e) => {
    setvalue({
      ...value,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Tai khoan</div>
        <input name="username" onChange={eventValueOnchang} />
        <div>Mat Khau</div>
        <input name="password" onChange={eventValueOnchang} />

        <div
          onClick={() => {
            console.log(value);
          }}
        >
          nut
        </div>
      </main>
    </>
  )
}
